### ISSUE TITLE
sendSignal without destination

### ISSUE THREAD

**Issue by zimmerle** [dbus-asio/dbus-asio#14]
I have failed to send a signal without a destination. In order to have it workable I have comment out the following parts of code -

https://github.com/dbus-asio/dbus-asio/blob/299bb807e7c12e37b03f78f82a05070980a6a61f/src/dbus_message_signal.cpp#L74-L79

As is, the dbus-monitor displays a destination attached to the signal
```
signal time=1617228413.170714 sender=:1.272 -> destination=org.foo.bar serial=58 path=/; interface=org.foo.bar member=Simple
```

After commented out the marshall part for destination I´ve got it -
```
signal time=1617231608.236017 sender=:1.321 -> destination=(null destination) serial=656 path=/; interface=org.foo.bar; member=Simple
```

Maybe we could have something as -
```c++
if (destination != nullptr) {
    DBus::Type::Struct sDestination;
    sDestination.add(DBus::Type::Byte(DBus::Message::Header::HEADER_DESTINATION));
    sDestination.add(DBus::Type::Variant(DBus::Type::String(destination)));
    array.add(sDestination);
}
```

Let me know if that makes sense to you guys, if so it will be a pleasure to send a pull request.

**Comment by zimmerle** [comment]
kudos to @cktakahasi, he helped a lot on the issue investigation.

**Comment by d12fk** [comment]
Seems to be copypasta from
https://github.com/dbus-asio/dbus-asio/blob/299bb807e7c12e37b03f78f82a05070980a6a61f/src/dbus_message_methodcall.cpp#L73-L78
where the comment makes sense. For signals the [dbus spec](https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-routing) explicitly mentions:

> When the message bus receives a signal, if the DESTINATION field is absent, it is considered to be a broadcast signal, and is sent to all applications with message matching rules that match the message.
[…]
> Unicast signal messages (those with a DESTINATION field) are not commonly used, …

This suggests nullptr as an default value for `destination` even.

**Comment by zimmerle** [comment]
> Seems to be copypasta from

?

> This suggests nullptr as an default value for `destination` eve

Is it working for you?

**Comment by d12fk** [comment]
Not sure why it shouldn't, have a patch ready, will open a PR soon.
Can you test it?
